project:
  type: website
  render:
    - "*.qmd"
    - "!calm/code-blocks/workflow-i.qmd"
    - "!calm/code-blocks/workflow-ii.qmd"
    - "!calm/code-blocks/workflow-iii.qmd"

website:
  title: "Finley Bacon"
  navbar:
    left:
      - href: index.qmd
        text: Home
  favicon: favicon.ico

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
  revealjs: 
    logo: favicon.ico
    link-external-icon: true
    incremental: true
    preview-links: true
    slide-number: c
    theme: dark
    transition: fade
    css: styles.css
